# Generated by Django 4.2 on 2026-03-13

import secrets

import app.models.profile
from django.db import migrations, models


def populate_profile_api_keys(apps, schema_editor):
    Profile = apps.get_model('app', 'Profile')
    existing_keys = set(Profile.objects.exclude(api_key__isnull=True).exclude(api_key='').values_list('api_key', flat=True))

    for profile in Profile.objects.filter(api_key__isnull=True) | Profile.objects.filter(api_key=''):
        api_key = secrets.token_hex(32)
        while api_key in existing_keys:
            api_key = secrets.token_hex(32)

        profile.api_key = api_key
        profile.save(update_fields=['api_key'])
        existing_keys.add(api_key)


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_update_json_and_bool_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='api_key',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='API key'),
        ),
        migrations.RunPython(populate_profile_api_keys, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='profile',
            name='api_key',
            field=models.CharField(default=app.models.profile.generate_api_key, editable=False, max_length=64, unique=True, verbose_name='API key'),
        ),
    ]

