# Generated by Django 4.2 on 2026-03-13

from django.db import migrations


THERMAL_OPTIONS = [
    {"name": "radiometric-calibration", "value": "camera"},
    {"name": "texturing-skip-global-seam-leveling", "value": True},
    {"name": "auto-boundary", "value": True},
    {"name": "pc-quality", "value": "high"},
    {"name": "dsm", "value": True},
    {"name": "orthophoto-compression", "value": "DEFLATE"},
    {"name": "build-overviews", "value": True},
    {"name": "cog", "value": True},
]


def add_thermal_preset(apps, schema_editor):
    Preset = apps.get_model('app', 'Preset')
    Preset.objects.get_or_create(
        name='Thermal',
        system=True,
        defaults={'options': THERMAL_OPTIONS},
    )


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_profile_api_key'),
    ]

    operations = [
        migrations.RunPython(add_thermal_preset, migrations.RunPython.noop),
    ]
