# Generated by Django 4.2.16 on 2026-03-13 08:28

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_add_thermal_preset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='border',
            field=colorfield.fields.ColorField(default='#d1d5db', help_text='The color of most borders.', max_length=18, verbose_name='Border'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='button_danger',
            field=colorfield.fields.ColorField(default='#b91c1c', help_text='Delete button color.', max_length=18, verbose_name='Button Danger'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='button_default',
            field=colorfield.fields.ColorField(default='#475569', help_text='Default button color.', max_length=18, verbose_name='Button Default'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='button_primary',
            field=colorfield.fields.ColorField(default='#0b63ce', help_text='Primary button color.', max_length=18, verbose_name='Button Primary'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='dialog_warning',
            field=colorfield.fields.ColorField(default='#b45309', help_text='The border color of warning dialogs.', max_length=18, verbose_name='Dialog Warning'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='failed',
            field=colorfield.fields.ColorField(default='#fee2e2', help_text='The background color of failed notifications.', max_length=18, verbose_name='Failed'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='header_background',
            field=colorfield.fields.ColorField(default='#0b63ce', help_text="Background color of the site's header.", max_length=18, verbose_name='Header Background'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='highlight',
            field=colorfield.fields.ColorField(default='#eef2f7', help_text='The background color of panels and some borders.', max_length=18, verbose_name='Highlight'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='primary',
            field=colorfield.fields.ColorField(default='#1f2937', help_text='Most text, icons, and borders.', max_length=18, verbose_name='Primary'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='secondary',
            field=colorfield.fields.ColorField(default='#f8fafc', help_text='The main background color, and text color of some buttons.', max_length=18, verbose_name='Secondary'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='success',
            field=colorfield.fields.ColorField(default='#dcfce7', help_text='The background color of success notifications.', max_length=18, verbose_name='Success'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='tertiary',
            field=colorfield.fields.ColorField(default='#0f62fe', help_text='Navigation links.', max_length=18, verbose_name='Tertiary'),
        ),
    ]
