# Generated by Django 4.2 on 2026-04-26

from django.db import migrations


DJI_DRONE_OPTIONS = [
    {"name": "auto-boundary", "value": True},
    {"name": "sfm-algorithm", "value": "triangulation"},
    {"name": "matcher-type", "value": "flann"},
    {"name": "matcher-neighbors", "value": 8},
    {"name": "feature-quality", "value": "ultra"},
    {"name": "min-num-features", "value": "18000"},
    {"name": "pc-quality", "value": "high"},
    {"name": "dsm", "value": True},
    {"name": "use-3dmesh", "value": True},
    {"name": "mesh-octree-depth", "value": "12"},
    {"name": "mesh-size", "value": "300000"},
    {"name": "orthophoto-compression", "value": "DEFLATE"},
    {"name": "build-overviews", "value": True},
    {"name": "cog", "value": True},
]


def add_dji_drone_preset(apps, schema_editor):
    Preset = apps.get_model("app", "Preset")
    Preset.objects.get_or_create(
        name="DJI Drone",
        system=True,
        defaults={"options": DJI_DRONE_OPTIONS},
    )


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0048_alter_theme_border_alter_theme_button_danger_and_more"),
    ]

    operations = [
        migrations.RunPython(add_dji_drone_preset, migrations.RunPython.noop),
    ]
