# Generated by Codex on 2026-05-10

import app.models.project_design_overlay
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0050_add_project_issues'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDesignOverlay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('file', models.FileField(upload_to=app.models.project_design_overlay.design_overlay_upload_path, validators=[app.models.project_design_overlay.validate_design_overlay_file])),
                ('source_filename', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_design_overlays', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_overlays', to='app.project')),
            ],
            options={
                'verbose_name': 'Project Design Overlay',
                'verbose_name_plural': 'Project Design Overlays',
                'ordering': ('-updated_at', '-created_at'),
            },
        ),
    ]
