# Generated by Codex on 2026-05-13

from django.db import migrations, models


SYSTEM_PRESETS = {
    "Multispectral": {
        "description": "Calibrated multispectral processing for reflectance-aware drone imagery.",
        "options": [
            {"name": "auto-boundary", "value": True},
            {"name": "radiometric-calibration", "value": "camera"},
        ],
    },
    "Thermal": {
        "description": "Thermal orthomosaic workflow with radiometric calibration and high quality point cloud settings.",
        "options": [
            {"name": "auto-boundary", "value": True},
            {"name": "radiometric-calibration", "value": "camera"},
            {"name": "texturing-skip-global-seam-leveling", "value": True},
            {"name": "pc-quality", "value": "high"},
            {"name": "dsm", "value": True},
            {"name": "orthophoto-compression", "value": "DEFLATE"},
            {"name": "build-overviews", "value": True},
            {"name": "cog", "value": True},
        ],
    },
    "DJI Drone": {
        "description": "Balanced DJI workflow with stronger feature matching, DSM output, and web map overviews.",
        "options": [
            {"name": "auto-boundary", "value": True},
            {"name": "sfm-algorithm", "value": "triangulation"},
            {"name": "matcher-type", "value": "flann"},
            {"name": "matcher-neighbors", "value": 8},
            {"name": "feature-quality", "value": "ultra"},
            {"name": "min-num-features", "value": "18000"},
            {"name": "pc-quality", "value": "high"},
            {"name": "dsm", "value": True},
            {"name": "use-3dmesh", "value": True},
            {"name": "mesh-octree-depth", "value": "12"},
            {"name": "mesh-size", "value": "300000"},
            {"name": "orthophoto-compression", "value": "DEFLATE"},
            {"name": "build-overviews", "value": True},
            {"name": "cog", "value": True},
        ],
    },
    "Commercial 3D Model": {
        "description": "Best-quality textured mesh workflow for client deliverables. Slower and memory intensive; use full-resolution source images.",
        "options": [
            {"name": "auto-boundary", "value": True},
            {"name": "sfm-algorithm", "value": "triangulation"},
            {"name": "matcher-type", "value": "flann"},
            {"name": "matcher-neighbors", "value": 8},
            {"name": "feature-quality", "value": "ultra"},
            {"name": "min-num-features", "value": "30000"},
            {"name": "pc-quality", "value": "ultra"},
            {"name": "use-3dmesh", "value": True},
            {"name": "mesh-octree-depth", "value": "12"},
            {"name": "mesh-size", "value": "2000000"},
            {"name": "gltf", "value": True},
        ],
    },
    "Volume Analysis": {
        "description": "DSM-focused output for stockpiles, piles, and other volume measurement workflows.",
        "options": [
            {"name": "auto-boundary", "value": True},
            {"name": "dsm", "value": True},
            {"name": "dem-resolution", "value": "2"},
            {"name": "pc-quality", "value": "high"},
        ],
    },
    "3D Model": {
        "description": "General 3D mesh processing with high point cloud quality and moderate mesh density.",
        "options": [
            {"name": "auto-boundary", "value": True},
            {"name": "mesh-octree-depth", "value": "12"},
            {"name": "use-3dmesh", "value": True},
            {"name": "pc-quality", "value": "high"},
            {"name": "mesh-size", "value": "300000"},
        ],
    },
    "Buildings": {
        "description": "Aerial reconstruction preset tuned for buildings and structured surfaces.",
        "options": [
            {"name": "auto-boundary", "value": True},
            {"name": "mesh-size", "value": "300000"},
            {"name": "feature-quality", "value": "high"},
            {"name": "pc-quality", "value": "high"},
        ],
    },
    "Forest": {
        "description": "Feature-focused processing for vegetation and forested areas.",
        "options": [
            {"name": "auto-boundary", "value": True},
            {"name": "min-num-features", "value": "18000"},
            {"name": "use-3dmesh", "value": True},
            {"name": "feature-quality", "value": "medium"},
        ],
    },
    "DSM + DTM": {
        "description": "Generate both surface and terrain elevation models.",
        "options": [
            {"name": "auto-boundary", "value": True},
            {"name": "dsm", "value": True},
            {"name": "dtm", "value": True},
        ],
    },
    "Field": {
        "description": "Fast planar mapping for field datasets where a quick orthophoto is more important than 3D detail.",
        "options": [
            {"name": "sfm-algorithm", "value": "planar"},
            {"name": "fast-orthophoto", "value": True},
            {"name": "matcher-neighbors", "value": 4},
        ],
    },
    "Fast Orthophoto": {
        "description": "Quick orthophoto generation for preview or low-cost turnaround.",
        "options": [
            {"name": "auto-boundary", "value": True},
            {"name": "fast-orthophoto", "value": True},
        ],
    },
    "High Resolution": {
        "description": "Higher-resolution orthophoto and DSM output for detailed 2D inspection.",
        "options": [
            {"name": "auto-boundary", "value": True},
            {"name": "dsm", "value": True},
            {"name": "pc-quality", "value": "high"},
            {"name": "dem-resolution", "value": "2.0"},
            {"name": "orthophoto-resolution", "value": "2.0"},
        ],
    },
    "Default": {
        "description": "Safe default processing with automatic boundary and DSM generation.",
        "options": [
            {"name": "auto-boundary", "value": True},
            {"name": "dsm", "value": True},
        ],
    },
}


def seed_system_preset_descriptions(apps, schema_editor):
    Preset = apps.get_model("app", "Preset")
    for name, preset in SYSTEM_PRESETS.items():
        Preset.objects.update_or_create(
            name=name,
            system=True,
            defaults={
                "description": preset["description"],
                "options": preset["options"],
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0051_add_project_design_overlays"),
    ]

    operations = [
        migrations.AddField(
            model_name="preset",
            name="description",
            field=models.TextField(blank=True, default="", help_text="A short explanation of when to use this preset.", verbose_name="Description"),
        ),
        migrations.RunPython(seed_system_preset_descriptions, migrations.RunPython.noop),
    ]
