# Generated by Codex on 2026-05-14

from django.db import migrations


GAUSSIAN_SPLAT_SOURCE_PRESET = {
    "description": "Highest-detail reconstruction source preset for Gaussian Splat post-processing. Produces ultra-quality point cloud, camera shots, and textured model assets for an external splat trainer.",
    "options": [
        {"name": "auto-boundary", "value": True},
        {"name": "sfm-algorithm", "value": "triangulation"},
        {"name": "matcher-type", "value": "flann"},
        {"name": "matcher-neighbors", "value": 8},
        {"name": "feature-quality", "value": "ultra"},
        {"name": "min-num-features", "value": "30000"},
        {"name": "pc-quality", "value": "ultra"},
        {"name": "use-3dmesh", "value": True},
        {"name": "mesh-octree-depth", "value": "12"},
        {"name": "mesh-size", "value": "2000000"},
        {"name": "gltf", "value": True},
        {"name": "pc-las", "value": True},
    ],
}


def add_gaussian_splat_source_preset(apps, schema_editor):
    Preset = apps.get_model("app", "Preset")
    Preset.objects.update_or_create(
        name="Gaussian Splat Source",
        system=True,
        defaults=GAUSSIAN_SPLAT_SOURCE_PRESET,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0052_preset_descriptions_and_commercial_3d"),
    ]

    operations = [
        migrations.RunPython(add_gaussian_splat_source_preset, migrations.RunPython.noop),
    ]
