# Generated by Codex on 2026-05-17

import app.models.project_field_photo
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0053_add_gaussian_splat_source_preset'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFieldPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.FileField(upload_to=app.models.project_field_photo.field_photo_upload_path, validators=[app.models.project_field_photo.validate_field_photo_file])),
                ('source_filename', models.CharField(blank=True, default='', max_length=255)),
                ('location', models.JSONField(validators=[app.models.project_field_photo.validate_point_geometry])),
                ('is_360', models.BooleanField(default=False)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('heading', models.FloatField(blank=True, null=True)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_field_photos', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_photos', to='app.project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_photos', to='app.task')),
            ],
            options={
                'verbose_name': 'Project Field Photo',
                'verbose_name_plural': 'Project Field Photos',
                'ordering': ('-captured_at', '-updated_at', '-created_at'),
            },
        ),
    ]
