# Generated by Codex on 2026-05-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_add_project_field_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='openai_api_key',
            field=models.CharField(blank=True, default='', help_text='Server-side OpenAI API key for AI-assisted issue detection. Never expose this key to browsers or clients.', max_length=255, verbose_name='OpenAI API key'),
        ),
        migrations.AddField(
            model_name='setting',
            name='openai_model',
            field=models.CharField(blank=True, default='gpt-4.1-mini', help_text='OpenAI model used for AI-assisted issue detection.', max_length=80, verbose_name='OpenAI model'),
        ),
    ]
