# Generated by Codex on 2026-05-17

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import app.models.project_issue


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0055_add_ai_issue_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectClientShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('role', models.CharField(choices=[('viewer', 'Viewer'), ('reviewer', 'Reviewer')], db_index=True, default='viewer', max_length=24)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_client_shares', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_shares', to='app.project')),
            ],
            options={
                'verbose_name': 'Project Client Share',
                'verbose_name_plural': 'Project Client Shares',
                'ordering': ('-updated_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='ProjectClientComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=255)),
                ('author_email', models.EmailField(blank=True, default='', max_length=254)),
                ('body', models.TextField()),
                ('geometry', models.JSONField(blank=True, null=True, validators=[app.models.project_issue.validate_geojson_geometry])),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_comments', to='app.projectissue')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_comments', to='app.project')),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.projectclientshare')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_comments', to='app.task')),
            ],
            options={
                'verbose_name': 'Project Client Comment',
                'verbose_name_plural': 'Project Client Comments',
                'ordering': ('-created_at',),
            },
        ),
    ]
