# Generated by Codex on 2026-05-17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0056_add_client_portal'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('area', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('untested', 'Untested'), ('testing', 'Testing'), ('tested', 'Tested'), ('failing', 'Failing'), ('blocked', 'Blocked')], db_index=True, default='untested', max_length=24)),
                ('test_notes', models.TextField(blank=True, default='')),
                ('maintenance_notes', models.TextField(blank=True, default='')),
                ('evidence_url', models.URLField(blank=True, default='')),
                ('last_tested_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_tested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_validations_tested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feature Validation',
                'verbose_name_plural': 'Feature Validations',
                'ordering': ('area', 'name'),
            },
        ),
    ]
