# Generated by Codex on 2026-05-27

from django.db import migrations


COMMERCIAL_ORTHOMOSAIC_PRESETS = {
    "Architecture CAD Orthomosaic": {
        "description": (
            "High-resolution orthomosaic workflow for CAD/design overlay comparison, "
            "construction progress review, DSM/DTM deltas, and client reporting."
        ),
        "options": [
            {"name": "auto-boundary", "value": True},
            {"name": "sfm-algorithm", "value": "triangulation"},
            {"name": "matcher-type", "value": "flann"},
            {"name": "matcher-neighbors", "value": 8},
            {"name": "feature-quality", "value": "ultra"},
            {"name": "min-num-features", "value": "22000"},
            {"name": "pc-quality", "value": "high"},
            {"name": "dsm", "value": True},
            {"name": "dtm", "value": True},
            {"name": "dem-resolution", "value": "2.0"},
            {"name": "orthophoto-resolution", "value": "1.5"},
            {"name": "orthophoto-compression", "value": "DEFLATE"},
            {"name": "build-overviews", "value": True},
            {"name": "cog", "value": True},
        ],
    },
    "Agriculture Field Analysis": {
        "description": (
            "Field analysis orthomosaic workflow with radiometric calibration, "
            "plant-health formulas, DSM output, and COG exports."
        ),
        "options": [
            {"name": "auto-boundary", "value": True},
            {"name": "radiometric-calibration", "value": "camera"},
            {"name": "sfm-algorithm", "value": "planar"},
            {"name": "matcher-neighbors", "value": 4},
            {"name": "feature-quality", "value": "high"},
            {"name": "dsm", "value": True},
            {"name": "dem-resolution", "value": "5.0"},
            {"name": "orthophoto-resolution", "value": "3.0"},
            {"name": "orthophoto-compression", "value": "DEFLATE"},
            {"name": "build-overviews", "value": True},
            {"name": "cog", "value": True},
        ],
    },
    "Solar Panel Inspection": {
        "description": (
            "High-detail orthomosaic workflow for solar farm inspection, panel issue "
            "mapping, thermal follow-up, and client review."
        ),
        "options": [
            {"name": "auto-boundary", "value": True},
            {"name": "sfm-algorithm", "value": "triangulation"},
            {"name": "matcher-type", "value": "flann"},
            {"name": "matcher-neighbors", "value": 8},
            {"name": "feature-quality", "value": "ultra"},
            {"name": "min-num-features", "value": "25000"},
            {"name": "pc-quality", "value": "high"},
            {"name": "dsm", "value": True},
            {"name": "dem-resolution", "value": "1.0"},
            {"name": "orthophoto-resolution", "value": "1.0"},
            {"name": "texturing-skip-global-seam-leveling", "value": True},
            {"name": "orthophoto-compression", "value": "DEFLATE"},
            {"name": "build-overviews", "value": True},
            {"name": "cog", "value": True},
        ],
    },
}


def add_commercial_orthomosaic_presets(apps, schema_editor):
    Preset = apps.get_model("app", "Preset")
    for name, preset in COMMERCIAL_ORTHOMOSAIC_PRESETS.items():
        Preset.objects.update_or_create(
            name=name,
            system=True,
            defaults={
                "description": preset["description"],
                "options": preset["options"],
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0057_add_feature_validation"),
    ]

    operations = [
        migrations.RunPython(add_commercial_orthomosaic_presets, migrations.RunPython.noop),
    ]
