# Generated by Codex on 2026-05-29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0058_commercial_orthomosaic_presets"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectCommercialReadiness",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("package", models.CharField(choices=[("basic_orthomosaic", "Basic Orthomosaic"), ("architecture_cad", "Architecture CAD Orthomosaic"), ("agriculture_field", "Agriculture Field Analysis"), ("solar_inspection", "Solar Panel Inspection")], db_index=True, default="basic_orthomosaic", max_length=40)),
                ("deliverables_reviewed", models.BooleanField(default=False)),
                ("human_reviewed", models.BooleanField(default=False)),
                ("report_reviewed", models.BooleanField(default=False)),
                ("client_share_reviewed", models.BooleanField(default=False)),
                ("legal_disclaimer_reviewed", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("project", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="commercial_readiness", to="app.project")),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="updated_commercial_readiness_records", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Project Commercial Readiness",
                "verbose_name_plural": "Project Commercial Readiness",
            },
        ),
    ]
