# Generated by Codex on 2026-06-21

from django.db import migrations


REQUIRED_OPTIONS = (
    {"name": "texturing-single-material", "value": True},
    {"name": "3d-tiles", "value": True},
    {"name": "gltf", "value": True},
)

ADDED_OPTION_NAMES = {"texturing-single-material", "3d-tiles"}

PREVIOUS_DESCRIPTION = (
    "Best-quality textured mesh workflow for client deliverables. Slower and "
    "memory intensive; use full-resolution source images."
)


def enable_cesium_exports(apps, schema_editor):
    Preset = apps.get_model("app", "Preset")
    preset = Preset.objects.filter(name="Commercial 3D Model", system=True).first()
    if preset is None:
        return

    required_names = {option["name"] for option in REQUIRED_OPTIONS}
    options = [
        option for option in (preset.options or [])
        if option.get("name") not in required_names
    ]
    options.extend(REQUIRED_OPTIONS)
    preset.options = options
    preset.description = (
        "Best-quality textured mesh workflow with native OGC 3D Tiles and "
        "Cesium ion-compatible outputs. Slower and memory intensive; use "
        "full-resolution source images."
    )
    preset.save(update_fields=["description", "options"])


def disable_cesium_exports(apps, schema_editor):
    Preset = apps.get_model("app", "Preset")
    preset = Preset.objects.filter(name="Commercial 3D Model", system=True).first()
    if preset is None:
        return

    preset.options = [
        option for option in (preset.options or [])
        if option.get("name") not in ADDED_OPTION_NAMES
    ]
    preset.description = PREVIOUS_DESCRIPTION
    preset.save(update_fields=["description", "options"])


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0059_add_project_commercial_readiness"),
    ]

    operations = [
        migrations.RunPython(enable_cesium_exports, disable_cesium_exports),
    ]
