# Generated by Codex on 2026-06-22

import datetime

from django.db import migrations, models
import django.db.models.deletion


AIRTWIN_PRESET = {
    "description": (
        "AirTwin-ready survey export with GLB, orthophoto, report, camera "
        "positions, elevation models, point cloud, and native OGC 3D Tiles."
    ),
    "options": [
        {"name": "auto-boundary", "value": True},
        {"name": "gltf", "value": True},
        {"name": "dsm", "value": True},
        {"name": "dtm", "value": True},
        {"name": "3d-tiles", "value": True},
    ],
}


def add_airtwin_preset_and_completion_times(apps, schema_editor):
    Preset = apps.get_model("app", "Preset")
    Task = apps.get_model("app", "Task")
    Preset.objects.update_or_create(
        name="AirTwin Export",
        system=True,
        defaults=AIRTWIN_PRESET,
    )

    for task in Task.objects.filter(status=40, completed_at__isnull=True).iterator():
        completed_at = task.created_at
        if task.processing_time is not None and task.processing_time >= 0:
            completed_at += datetime.timedelta(milliseconds=task.processing_time)
        task.completed_at = completed_at
        task.save(update_fields=["completed_at"])


def remove_airtwin_preset(apps, schema_editor):
    Preset = apps.get_model("app", "Preset")
    Preset.objects.filter(name="AirTwin Export", system=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0060_enable_cesium_3d_tiles_preset"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="completed_at",
            field=models.DateTimeField(blank=True, help_text="Successful completion date", null=True, verbose_name="Completed at"),
        ),
        migrations.CreateModel(
            name="AirTwinWebhookDelivery",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_id", models.UUIDField(db_index=True, unique=True)),
                ("event", models.CharField(default="webodm.task.completed", max_length=80)),
                ("payload", models.JSONField(default=dict)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("retrying", "Retrying"), ("delivered", "Delivered"), ("failed", "Failed")], db_index=True, default="pending", max_length=20)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("response_status", models.PositiveIntegerField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
                ("next_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("task", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="airtwin_webhook_deliveries", to="app.task")),
            ],
            options={
                "verbose_name": "AirTwin webhook delivery",
                "verbose_name_plural": "AirTwin webhook deliveries",
                "ordering": ("-created_at",),
            },
        ),
        migrations.RunPython(add_airtwin_preset_and_completion_times, remove_airtwin_preset),
    ]
