# Generated by Codex on 2026-06-22

from django.db import migrations, models
import django.db.models.deletion


def backfill_airtwin_import_states(apps, schema_editor):
    AirTwinImportState = apps.get_model("app", "AirTwinImportState")
    AirTwinWebhookDelivery = apps.get_model("app", "AirTwinWebhookDelivery")

    for delivery in AirTwinWebhookDelivery.objects.order_by("created_at").iterator():
        AirTwinImportState.objects.update_or_create(
            task_id=delivery.task_id,
            defaults={
                "event_id": delivery.event_id,
                "status": "pending",
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0061_airtwin_integration"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "permissions": (("acknowledge_airtwin_import", "Can acknowledge AirTwin imports"),),
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
            },
        ),
        migrations.CreateModel(
            name="AirTwinImportState",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_id", models.UUIDField(db_index=True)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("importing", "Importing"), ("imported", "Imported"), ("failed", "Failed")], db_index=True, default="pending", max_length=20)),
                ("imported_assets", models.JSONField(blank=True, default=list)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True, default="")),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("imported_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("task", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="airtwin_import_state", to="app.task")),
            ],
            options={
                "verbose_name": "AirTwin import state",
                "verbose_name_plural": "AirTwin import states",
            },
        ),
        migrations.RunPython(backfill_airtwin_import_states, migrations.RunPython.noop),
    ]
